import React from 'react'
import "./about.styles.css"
import Imag1 from "./cap2.png"

const About = () => {
    return (
        <div className="aboutHeader" id="about-section">
                <h1>About Us</h1>
            <div className=" AboutContainer">

            <div className="About-content">
            <p>
            webpack finds all relative module references in CSS (they start with ./) and replaces them with the final paths from the compiled bundle. If you make a typo or accidentally delete an important file, you will see a compilation error, like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by webpack from content hashes. If the file content changes in the future, webpack will give it a different name in production so you don’t need to worry about long-term caching of assets.
            </p>
            </div>

             <div className="imag">
             <img src={Imag1} width="300px" className="aboutImg" alt="show"/>
             </div>

            </div>
        </div>
    )
}

export default About
